Repository geojupyter/jupytergis, pull requests merged in 2024-11, with the labels that each got.

#195 first draft of documentation for JupyterGIS
  docs/environment.yml
  docs/source/assets/lab_ext.webp
  docs/source/collab.rst
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/extension.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/python_api.rst
Labels: documentation

#198 Add nodata to geotiff source
  packages/base/src/mainview/mainView.tsx
Labels: bug

#200 Add a min-height to the toolbar separator
  python/jupytergis_lab/style/base.css
Labels: bug

#203 UI-tests fix: Pin Jupyter Lab 4.2
  .github/workflows/build.yml
Labels: bug

#202 Fix focus bug
  packages/base/src/dialogs/symbology/components/color_stops/StopRow.tsx
Labels: bug

#206 Fix links to docs and lite deployment
  README.md
Labels: documentation

#204 Update to jupyter-collaboration>=3
  .github/workflows/build.yml
  package.json
  packages/base/package.json
  packages/base/src/mainview/mainView.tsx
  packages/base/src/toolbar/widget.tsx
  packages/schema/package.json
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_core/package.json
  python/jupytergis_core/pyproject.toml
  python/jupytergis_core/src/factory.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/package.json
  python/jupytergis_lab/pyproject.toml
  python/jupytergis_lab/src/notebookrenderer.ts
  python/jupytergis_qgis/package.json
  python/jupytergis_qgis/pyproject.toml
  python/jupytergis_qgis/src/plugins.ts
  ui-tests/package.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#210 Open jgis files with json viewer
  python/jupytergis_core/src/jgisplugin/plugins.ts
Labels: enhancement

#199 Add support for other projections
  package.json
  packages/base/src/mainview/mainView.tsx
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py
  yarn.lock
Labels: enhancement

#213 Disable docprovider-extension in lite deployment
  docs/jupyter-lite.json
Labels: maintenance
