Repository geojupyter/jupytergis, pull requests merged in 2024-06, with the labels that each got.

#2 Add CI
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/update_galata_references.yaml
  README.md
  examples/test.jGIS
  python/jupytergis/jupytergis/__init__.py
  python/jupytergis_lab/style/base.css
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/sketcher.spec.ts
  ui-tests/tests/sketcher.spec.ts-snapshots/Sketcher-Circle-test-jcad-linux.png
  ui-tests/tests/sketcher.spec.ts-snapshots/Sketcher-Display-test-jcad-linux.png
  ui-tests/tests/tree.spec.ts
  ui-tests/tests/tree.spec.ts-snapshots/Tree-Display-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-Cut-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/MultiSelect-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Add-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Edit-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Operator-Remove-test-jcad-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-3M-CONNECTOR-STEP-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-fan-stl-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jGIS-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jcad-linux.png
Labels: maintenance

#5 Add jupyterlab build dependency
  requirements-build.txt
Labels: maintenance

#6 Allow for creating tile layers
  examples/test.jGIS
  packages/base/package.json
  packages/base/src/commands.ts
  packages/base/src/mainview/mainview.tsx
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/src/tools.ts
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/jgis.json
  packages/schema/src/schema/rasterlayer.json
  packages/schema/src/schema/rastersource.json
  packages/schema/src/types.ts
  python/jupytergis_core/install.json
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  python/jupytergis_core/pyproject.toml
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/src/index.ts
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  yarn.lock
Labels: enhancement

#15 Linting
  .eslintignore
  .eslintrc.js
  .github/workflows/build.yml
  .prettierignore
  .prettierrc
  lerna.json
  package.json
  packages/base/src/commands.ts
  packages/base/src/mainview/mainview.tsx
  packages/base/src/mainview/mainviewmodel.ts
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/base/src/svg.d.ts
  packages/base/src/tools.ts
  packages/base/src/widget.tsx
  packages/schema/schema.js
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/jgis.json
  packages/schema/src/schema/rasterlayer.json
  packages/schema/src/schema/rastersource.json
  python/jupytergis_core/src/jgisplugin/modelfactory.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_core/style/index.js
  python/jupytergis_lab/src/index.ts
  python/jupytergis_lab/src/notebookrenderer.ts
  python/jupytergis_lab/style/index.js
  ui-tests/playwright.config.js
  yarn.lock
Labels: maintenance

#18 Fix the collaborative document
  python/jupytergis_core/src/jgisplugin/plugins.ts
Labels: bug

#17 Add a layers panel
  examples/test.jGIS
  packages/base/src/icons.ts
  packages/base/src/mainview/mainview.tsx
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/style/base.css
  packages/base/style/icons/nonvisibility.svg
  packages/base/style/icons/raster.svg
  packages/base/style/icons/visibility.svg
  packages/base/style/index.css
  packages/base/style/index.js
  packages/base/style/leftPanel.css
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/jgis.json
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/style/base.css
  ui-tests/playwright.config.js
  ui-tests/tests/left-panel.spec.ts
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-hover-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-not-selected-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-not-visible-icon-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-selected-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-visible-icon-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/raster-layer-icon-linux.png
Labels: enhancement

#19 Use event in main view
  examples/test.jGIS
  packages/base/src/mainview/mainview.tsx
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  ui-tests/tests/left-panel.spec.ts
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-hidden-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-not-hidden-linux.png
Labels: enhancement
