Repository geojupyter/jupytergis, pull requests merged in 2024-09, with the labels that each got.

#119 Use extent instead of center position and zoom
  examples/3d_terrain.jGIS
  packages/base/src/mainview/mainView.tsx
  packages/base/src/panelview/components/filter-panel/Filter.tsx
  packages/base/src/tools.ts
  packages/schema/src/schema/jgis.json
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py
Labels: enhancement

#124 Some code cleaning
  packages/base/package.json
  packages/base/src/dialogs/components/color-expression/StopRow.tsx
  packages/base/src/dialogs/layerBrowserDialog.tsx
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/tilesourceform.ts
  packages/base/src/formbuilder/objectform/vectorlayerform.ts
  packages/base/src/mainview/mainView.tsx
  packages/base/src/panelview/components/filter-panel/Filter.tsx
  packages/base/src/panelview/components/filter-panel/FilterRow.tsx
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/tools.ts
  packages/schema/src/model.ts
  python/jupytergis_qgis/src/plugins.ts
  tsconfigbase.json
  ui-tests/tests/gis-files/context-test.jGIS
  ui-tests/tests/gis-files/empty-france.jGIS
  ui-tests/tests/gis-files/filter-test.jGIS
  ui-tests/tests/gis-files/panel-test.jGIS
  ui-tests/tests/gis-files/test.jGIS
  yarn.lock
Labels: maintenance

#126 Fix form for vectortilelayer
  packages/base/src/formbuilder/formselectors.ts
Labels: bug

#123 Add symbology panel
  examples/geotif.qgz
  examples/geotiff-2.jGIS
  examples/geotiff.jGIS
  packages/base/package.json
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/dialogs/colorExpressionDialog.tsx
  packages/base/src/dialogs/components/color-expression/StopRow.tsx
  packages/base/src/dialogs/components/symbology/BandRendering.tsx
  packages/base/src/dialogs/components/symbology/BandRow.tsx
  packages/base/src/dialogs/components/symbology/SingleBandPseudoColor.tsx
  packages/base/src/dialogs/components/symbology/StopRow.tsx
  packages/base/src/dialogs/symbologyDialog.tsx
  packages/base/src/formbuilder/formselectors.ts
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/webGlLayerForm.tsx
  packages/base/src/mainview/mainView.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/style/base.css
  packages/base/style/symbologyDialog.css
  python/jupytergis_core/extension.webpack.config.js
  python/jupytergis_core/package.json
  python/jupytergis_lab/src/index.ts
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-hidden-linux.png
  yarn.lock
Labels: enhancement

#130 Fix CI
  .github/workflows/build.yml
  ui-tests/tests/ui.spec.ts
Labels: maintenance

#129 Small context menus improvements + add symbology menu
  packages/base/src/commands.ts
  python/jupytergis_lab/src/index.ts
  ui-tests/tests/contextmenu.spec.ts
Labels: enhancement

#131 Set Qt offscreen in jupytergis-qgis
  .github/workflows/build.yml
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
Labels: enhancement

#132 Add basic README
  CONTRIBUTING.md
  README.md
  jupytergis.png
Labels: documentation

#133 Update screenshot to show collaborators
  jupytergis.png
Labels: documentation

#134 Update releaser workflows
  .github/workflows/check-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#137 Enable min/max values for tif layers
  examples/geotiff-2.jGIS
  packages/base/src/dialogs/components/symbology/BandRow.tsx
  packages/base/src/dialogs/components/symbology/SingleBandPseudoColor.tsx
  packages/base/src/dialogs/components/symbology/StopRow.tsx
  packages/base/src/mainview/mainView.tsx
  packages/base/style/symbologyDialog.css
  packages/schema/src/schema/geoTiffSource.json
Labels: enhancement

#135 Improve toolbar
  examples/geotif.qgz
  examples/geotiff.qgz
  packages/base/src/constants.ts
  packages/base/src/toolbar/widget.tsx
  packages/base/style/icons/geojson.svg
  packages/base/style/icons/mound.svg
  ui-tests/tests/geojson-layers.spec.ts
Labels: enhancement

#136 Console view
  packages/base/package.json
  packages/base/src/commands.ts
  packages/base/src/console/consoleview.ts
  packages/base/src/console/index.ts
  packages/base/src/constants.ts
  packages/base/src/mainview/index.ts
  packages/base/src/mainview/mainviewwidget.tsx
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/components/sources.tsx
  packages/base/src/toolbar/usertoolbaritem.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/src/widget.ts
  packages/base/src/widget.tsx
  packages/schema/src/interfaces.ts
  python/jupytergis_core/src/factory.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/jupytergis_lab/__init__.py
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/package.json
  python/jupytergis_lab/pyproject.toml
  python/jupytergis_lab/src/index.ts
  python/jupytergis_lab/style/base.css
  python/jupytergis_qgis/package.json
  python/jupytergis_qgis/src/plugins.ts
  yarn.lock
Labels: enhancement

#141 Add back ShapeFile Support
  packages/base/package.json
  packages/base/src/mainview/mainView.tsx
  yarn.lock
Labels: bug

#142 Add the scale back
  packages/base/src/mainview/mainView.tsx
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-hidden-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-not-hidden-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
Labels: bug

#138 Fix jupyterlite issue
  .github/workflows/build.yml
  packages/base/src/toolbar/usertoolbaritem.tsx
Labels: bug

#145 Notebook renderer: Use SharedModelFactory to create shared model
  python/jupytergis_lab/src/notebookrenderer.ts
Labels: maintenance

#143 Add handling for line type in vector layer
  packages/base/src/mainview/mainView.tsx
Labels: enhancement

#139 Tif layer notebook API
  packages/base/src/commands.ts
  packages/base/src/dialogs/components/symbology/SingleBandPseudoColor.tsx
  packages/base/src/mainview/mainView.tsx
  packages/schema/src/schema/geoTiffSource.json
  packages/schema/src/schema/webGlLayer.json
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/objects/__init__.py
  python/jupytergis_lab/jupytergis_lab/notebook/tests/test_api.py
Labels: enhancement

#148 Build the lite deployment even if integration tests don't pass
  .github/workflows/build.yml
Labels: enhancement

#146 Update geotiff example
  examples/geotiff.jGIS
Labels: bug

#147 Raise an ImportError for the Python API in JupyterLite for now
  python/jupytergis_lab/jupytergis_lab/__init__.py
Labels: enhancement

#149 Trigger snapshots update
  ui-tests/tests/geojson-layers.spec.ts-snapshots/geoJSON-layer-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-not-hidden-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
Labels: maintenance

#150 Use base URL for accessing gdal assets
  packages/base/src/dialogs/components/symbology/SingleBandPseudoColor.tsx
Labels: bug

#151 Add ruff for linting and formatting
  .pre-commit-config.yaml
  docs/source/index.rst
  examples/3d_terrain.jGIS
  examples/Notebook.ipynb
  examples/buildings.jGIS
  examples/earthquakes-no-filter.jGIS
  examples/earthquakes.jGIS
  examples/france_hiking.jGIS
  examples/geotiff-2.jGIS
  examples/geotiff.jGIS
  examples/image_test.jGIS
  examples/pmtiles-raster.jGIS
  examples/pmtiles-vector.jGIS
  examples/test.jGIS
  packages/base/rasterlayer_gallery_generator.py
  pyproject.toml
  python/jupytergis_core/jupytergis_core/__init__.py
  python/jupytergis_core/jupytergis_core/handler.py
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  python/jupytergis_lab/jupytergis_lab/__init__.py
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/tests/test_api.py
  python/jupytergis_lab/jupytergis_lab/notebook/utils.py
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  python/jupytergis_qgis/jupytergis_qgis/qgis_ydoc.py
  python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py
  requirements-build.txt
  ui-tests/tests/gis-files/context-test.jGIS
  ui-tests/tests/gis-files/empty-france.jGIS
  ui-tests/tests/gis-files/filter-test.jGIS
  ui-tests/tests/gis-files/panel-test.jGIS
  ui-tests/tests/gis-files/test.jGIS
  ui-tests/tests/notebooks/Notebook.ipynb
Labels: maintenance

#153 Fix update option in main view
  packages/base/src/mainview/mainView.tsx
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
Labels: bug

#152 Vector symbology
  examples/earthquakes-no-filter.jGIS
  examples/earthquakes.jGIS
  examples/geojson.jGIS
  examples/geotiff-2.jGIS
  examples/geotiff.jGIS
  examples/test.jGIS
  packages/base/src/dialogs/components/symbology/Graduated.tsx
  packages/base/src/dialogs/components/symbology/SimpleSymbol.tsx
  packages/base/src/dialogs/components/symbology/SingleBandPseudoColor.tsx
  packages/base/src/dialogs/components/symbology/StopRow.tsx
  packages/base/src/dialogs/components/symbology/VectorRendering.tsx
  packages/base/src/dialogs/symbologyDialog.tsx
  packages/base/src/formbuilder/objectform/vectorlayerform.ts
  packages/base/src/mainview/mainView.tsx
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/tools.ts
  packages/base/style/symbologyDialog.css
  ui-tests/tests/filters.spec.ts-snapshots/no-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/one-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/two-filter-linux.png
  ui-tests/tests/geojson-layers.spec.ts-snapshots/geoJSON-layer-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-hidden-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
Labels: enhancement

#156 Improve gdal initialization
  packages/base/package.json
  packages/base/src/dialogs/components/symbology/SingleBandPseudoColor.tsx
  packages/base/src/gdal.ts
  python/jupytergis_core/extension.webpack.config.js
  python/jupytergis_core/package.json
Labels: enhancement

#159 Fix the update layers
  packages/base/src/mainview/mainView.tsx
Labels: bug

#161 Update snapshots
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-hidden-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-not-hidden-linux.png
Labels: maintenance

#160 Hotfix qgis loader for vector tile layer
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py
Labels: bug

#162 Cleanup examples
  examples/earthquakes.jGIS
  examples/france_hiking.jGIS
  examples/france_regions.json
  examples/hillshade.jGIS
  examples/image.jGIS
  examples/test.jGIS
Labels: maintenance
