Repository geojupyter/jupytergis, pull requests merged in 2024-07, with the labels that each got.

#21 Drop YJGIS 'source' root type
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
Labels: maintenance

#23 Clean the layer panel if there is no GIS widget in the tracker
  packages/base/src/panelview/leftpanel.tsx
  ui-tests/tests/left-panel.spec.ts
Labels: bug

#20 Object properties panel
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/objectproperties.tsx
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
Labels: enhancement

#22 Add layer in the layers tree from the GIS model
  examples/test.jGIS
  packages/base/src/commands.ts
  packages/base/src/mainview/mainview.tsx
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/style/leftPanel.css
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/jgis.json
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  ui-tests/tests/left-panel.spec.ts
Labels: enhancement

#25 Remove the installation of server extension
  scripts/dev-install.py
Labels: maintenance

#26 Fix new layer in map
  packages/base/src/mainview/mainview.tsx
  packages/schema/src/model.ts
Labels: bug

#16 Add raster layer gallery
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .gitignore
  package.json
  packages/base/package.json
  packages/base/rasterlayer_gallery_generator.py
  packages/base/src/commands.ts
  packages/base/src/layerBrowser/layerBrowserDialog.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/src/tools.ts
  packages/base/src/types.ts
  packages/base/style/base.css
  packages/base/style/layerBrowser.css
  packages/schema/package.json
  packages/schema/src/interfaces.ts
  packages/schema/src/schema/rastersource.json
  packages/schema/src/token.ts
  python/jupytergis_core/package.json
  python/jupytergis_core/src/index.ts
  python/jupytergis_core/src/layerBrowserRegistry.ts
  python/jupytergis_core/src/plugin.ts
  python/jupytergis_lab/package.json
  python/jupytergis_lab/src/index.ts
  requirements-build.txt
  tsconfigbase.json
  ui-tests/tests/layer-browser.spec.ts
  yarn.lock
Labels: enhancement

#27 Fix thumnbails in script
  packages/base/rasterlayer_gallery_generator.py
Labels: bug

#29 Rework object properties + format url properly
  packages/base/rasterlayer_gallery_generator.py
  packages/base/src/formdialog.tsx
  packages/base/src/layerBrowser/layerBrowserDialog.tsx
  packages/base/src/mainview/mainview.tsx
  packages/base/src/panelview/formbuilder.tsx
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/tools.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/rasterlayer.json
  packages/schema/src/schema/rastersource.json
Labels: enhancement

#31 Cleanup
  packages/base/src/commands.ts
  packages/base/src/formdialog.tsx
  packages/base/src/panelview/formbuilder.tsx
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/tools.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
Labels: maintenance

#32 Rework custom raster layer creation
  .gitignore
  packages/base/rasterlayer_gallery/custom_raster.png
  packages/base/src/commands.ts
  packages/base/src/declaration.d.ts
  packages/base/src/formdialog.tsx
  packages/base/src/layerBrowser/layerBrowserDialog.tsx
  packages/base/src/panelview/formbuilder.tsx
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/src/tools.ts
  packages/base/style/layerBrowser.css
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  ui-tests/tests/layer-browser.spec.ts
Labels: enhancement

#42 Fix opacity step
  packages/schema/src/schema/rasterlayer.json
  packages/schema/src/schema/vectorLayer.json
Labels: bug

#43 Attribution controls and navigation controls
  packages/base/src/mainview/mainview.tsx
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-hidden-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
Labels: enhancement

#45 Fix linting
  packages/base/src/mainview/mainview.tsx
  ui-tests/tests/geojson-layers.spec.ts
Labels: maintenance

#38 Notebook API
  .github/workflows/build.yml
  examples/Notebook.ipynb
  examples/test.jGIS
  packages/base/src/mainview/mainview.tsx
  packages/base/style/base.css
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/jgis.json
  packages/schema/src/schema/rasterlayer.json
  packages/schema/src/schema/rastersource.json
  python/jupytergis_core/src/factory.ts
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/objects/__init__.py
  ui-tests/tests/geojson-layers.spec.ts
  ui-tests/tests/geojson-layers.spec.ts-snapshots/geoJSON-layer-linux.png
  ui-tests/tests/gis-files/france_regions.json
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebooks/Notebook.ipynb
Labels: enhancement

#49 Files sort keys
  examples/test.jGIS
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-hidden-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/top-layer-not-hidden-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jGIS-linux.png
Labels: bug

#37 Vector tile source
  examples/buildings.jGIS
  packages/base/src/commands.ts
  packages/base/src/formdialog.tsx
  packages/base/src/mainview/mainview.tsx
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/toolbar/widget.tsx
  packages/schema/src/schema/jgis.json
  packages/schema/src/schema/vectorlayer.json
  packages/schema/src/schema/vectortilesource.json
  packages/schema/src/types.ts
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/objects/__init__.py
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebooks/Notebook.ipynb
Labels: enhancement

#50 Update minZoom value for buildings example
  examples/buildings.jGIS
Labels: enhancement

#53 Remove OCC from build env
  .github/workflows/build.yml
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#48 Add Context menu to layer tree items
  packages/base/src/commands.ts
  packages/base/src/mainview/mainview.tsx
  packages/base/src/panelview/components/layers.tsx
  packages/base/style/leftPanel.css
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/src/index.ts
Labels: enhancement

#57 Fix undo bug
  packages/base/src/mainview/mainview.tsx
  packages/base/style/leftPanel.css
  ui-tests/tests/left-panel.spec.ts
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-hover-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-not-selected-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-not-visible-icon-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-selected-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-visible-icon-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/raster-layer-icon-linux.png
Labels: bug

#63 Pin reacttrs
  python/jupytergis_lab/pyproject.toml
Labels: bug

#61 Fix context menu issue
  python/jupytergis_lab/src/index.ts
Labels: bug

#65 Bump ypywidgets>=0.9.0
  python/jupytergis_lab/pyproject.toml
Labels: maintenance

#55 Refactor form building
  packages/base/src/commands.ts
  packages/base/src/dialogs/formdialog.tsx
  packages/base/src/dialogs/geoJsonLayerDialog.tsx
  packages/base/src/dialogs/layerBrowserDialog.tsx
  packages/base/src/formbuilder/creationform.tsx
  packages/base/src/formbuilder/editform.tsx
  packages/base/src/formbuilder/formselectors.ts
  packages/base/src/formbuilder/index.ts
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  packages/base/src/formbuilder/objectform/layerform.ts
  packages/base/src/formbuilder/objectform/tilesourceform.ts
  packages/base/src/formbuilder/objectform/vectorlayerform.ts
  packages/base/src/formdialog.tsx
  packages/base/src/index.ts
  packages/base/src/panelview/formbuilder.tsx
  packages/base/src/panelview/index.ts
  packages/base/src/panelview/objectproperties.tsx
  packages/base/style/dialog.css
  packages/base/style/layerBrowser.css
  packages/schema/src/interfaces.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/style/base.css
  ui-tests/tests/geojson-layers.spec.ts
  ui-tests/tests/left-panel.spec.ts
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-hover-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-not-selected-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-selected-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
Labels: maintenance

#60 Add a source panel
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/index.ts
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/components/sources.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/model.ts
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/style/leftPanel.css
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_lab/src/index.ts
  ui-tests/tests/left-panel.spec.ts
  ui-tests/tests/left-panel.spec.ts-snapshots/raster-layer-icon-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/source-hover-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/source-selected-linux.png
Labels: enhancement

#58 Keyboard shortcuts
  packages/base/src/panelview/components/layers.tsx
  packages/base/style/leftPanel.css
  python/jupytergis_lab/src/index.ts
  ui-tests/tests/contextmenu.spec.ts
Labels: enhancement

#70 Fix source removal
  packages/base/src/mainview/mainview.tsx
Labels: bug

#73 Rework tests
  ui-tests/tests/contextmenu.spec.ts
  ui-tests/tests/gis-files/test.jGIS
  ui-tests/tests/left-panel.spec.ts
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-hover-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-not-selected-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-not-visible-icon-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-selected-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/layer-visible-icon-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/source-hover-linux.png
  ui-tests/tests/left-panel.spec.ts-snapshots/source-selected-linux.png
Labels: maintenance

#68 Add keyboard shortcuts to sources panel
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/components/sources.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/style/leftPanel.css
  python/jupytergis_lab/src/index.ts
Labels: enhancement

#74 Improve form CSS
  packages/base/style/base.css
Labels: enhancement

#64 Add support for 3d displays
  examples/3d_terrain.jGIS
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/dialogs/terrainDialog.tsx
  packages/base/src/icons.ts
  packages/base/src/mainview/mainview.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/style/base.css
  packages/base/style/icons/mound.svg
  packages/base/style/terrainDialog.css
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/hillshadeLayer.json
  packages/schema/src/schema/jgis.json
  packages/schema/src/schema/rasterDemSource.json
  packages/schema/src/types.ts
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/src/index.ts
  python/jupytergis_lab/style/base.css
  tsconfigbase.json
  ui-tests/tests/contextmenu.spec.ts
  ui-tests/tests/left-panel.spec.ts
Labels: enhancement

#76 Add color picker for hillshade shadow color
  packages/base/src/formbuilder/formselectors.ts
  packages/base/src/formbuilder/objectform/hillshadeLayerForm.ts
Labels: enhancement

#75 Add pitch and bearing to map options
  examples/3d_terrain.jGIS
  examples/test.jGIS
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/mainview/mainview.tsx
  packages/schema/src/model.ts
  packages/schema/src/schema/jgis.json
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/src/index.ts
  ui-tests/tests/contextmenu.spec.ts
  ui-tests/tests/gis-files/test.jGIS
  ui-tests/tests/ui.spec.ts
Labels: enhancement

#28 Support importing QGIS project
  .github/workflows/test.yml
  environment-dev.yml
  python/jupytergis_core/tests/files/project0.qgs
  python/jupytergis_core/tests/test_qgis.py
  python/jupytergis_core/tests/utils.py
Labels: enhancement

#77 New file fix
  python/jupytergis_core/src/jgisplugin/plugins.ts
  ui-tests/tests/new-file.spec.ts
Labels: bug

#81 Update Contributing Guide for Developer Installation
  CONTRIBUTING.md
Labels: documentation

#80 Fix a wrong comparison handling the unused statut of a source
  packages/base/src/panelview/components/sources.tsx
Labels: bug

#79 Add image and video support
  examples/video_test.jGIS
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/mainview/mainview.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/style/base.css
  packages/schema/src/schema/imageSource.json
  packages/schema/src/schema/jgis.json
  packages/schema/src/schema/rasterlayer.json
  packages/schema/src/schema/videoSource.json
  packages/schema/src/types.ts
  python/jupytergis_lab/src/index.ts
Labels: enhancement

#84 Disable form validation at startup if it is invalid
  packages/base/src/dialogs/formdialog.tsx
  packages/base/src/formbuilder/creationform.tsx
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  ui-tests/tests/geojson-layers.spec.ts
  ui-tests/tests/left-panel.spec.ts
Labels: bug

#83 Add python API for image and video layers
  examples/Notebook.ipynb
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/objects/__init__.py
Labels: enhancement

#85 Reverse the layer order in side panel
  packages/base/src/panelview/components/layers.tsx
  ui-tests/tests/contextmenu.spec.ts
  ui-tests/tests/left-panel.spec.ts
Labels: enhancement
