Repository geojupyter/jupytergis, pull requests merged in 2024-12, with the labels that each got.

#219 JupyterLite: do not fail on file validation issues
  packages/schema/src/model.ts
Labels: enhancement

#221 Commit gallery in the repo
  .eslintignore
  .gitignore
  .prettierignore
  packages/base/package.json
  packages/base/rasterlayer_gallery/Gaode-Normal.png
  packages/base/rasterlayer_gallery/Gaode-Satellite.png
  packages/base/rasterlayer_gallery/NASAGIBS-ASTER_GDEM_Greyscale_Shaded_Relief.png
  packages/base/rasterlayer_gallery/NASAGIBS-ModisAquaBands721CR.png
  packages/base/rasterlayer_gallery/NASAGIBS-ModisAquaTrueColorCR.png
  packages/base/rasterlayer_gallery/NASAGIBS-ModisTerraAOD.png
  packages/base/rasterlayer_gallery/NASAGIBS-ModisTerraBands367CR.png
  packages/base/rasterlayer_gallery/NASAGIBS-ModisTerraBands721CR.png
  packages/base/rasterlayer_gallery/NASAGIBS-ModisTerraChlorophyll.png
  packages/base/rasterlayer_gallery/NASAGIBS-ModisTerraLSTDay.png
  packages/base/rasterlayer_gallery/NASAGIBS-ModisTerraSnowCover.png
  packages/base/rasterlayer_gallery/NASAGIBS-ModisTerraTrueColorCR.png
  packages/base/rasterlayer_gallery/NASAGIBS-ViirsEarthAtNight2012.png
  packages/base/rasterlayer_gallery/NASAGIBS-ViirsTrueColorCR.png
  packages/base/rasterlayer_gallery/OPNVKarte.png
  packages/base/rasterlayer_gallery/OpenRailwayMap.png
  packages/base/rasterlayer_gallery/OpenStreetMap-BZH.png
  packages/base/rasterlayer_gallery/OpenStreetMap-CH.png
  packages/base/rasterlayer_gallery/OpenStreetMap-DE.png
  packages/base/rasterlayer_gallery/OpenStreetMap-France.png
  packages/base/rasterlayer_gallery/OpenStreetMap-HOT.png
  packages/base/rasterlayer_gallery/OpenStreetMap-Mapnik.png
  packages/base/rasterlayer_gallery/OpenTopoMap.png
  packages/base/rasterlayer_gallery/Strava-All.png
  packages/base/rasterlayer_gallery/Strava-Ride.png
  packages/base/rasterlayer_gallery/Strava-Run.png
  packages/base/rasterlayer_gallery/Strava-Water.png
  packages/base/rasterlayer_gallery/Strava-Winter.png
  packages/base/rasterlayer_gallery/USGS-USImagery.png
  packages/base/rasterlayer_gallery/USGS-USImageryTopo.png
  packages/base/rasterlayer_gallery/USGS-USTopo.png
  packages/base/rasterlayer_gallery/WaymarkedTrails-cycling.png
  packages/base/rasterlayer_gallery/WaymarkedTrails-hiking.png
  packages/base/rasterlayer_gallery/WaymarkedTrails-mtb.png
  packages/base/rasterlayer_gallery/WaymarkedTrails-riding.png
  packages/base/rasterlayer_gallery/WaymarkedTrails-skating.png
  packages/base/rasterlayer_gallery/WaymarkedTrails-slopes.png
  packages/base/rasterlayer_gallery/raster_layer_gallery.json
Labels: maintenance

#223 Fix check-release workflow
  .github/workflows/check-release.yml
Labels: bug, maintenance

#226 Update README demo link to open `france_hiking.jGIS`
  README.md
Labels: documentation

#165 Embed GeoJSON schema in the project to improve build reliability
  packages/schema/cacheGeoJSONSchema.js
  packages/schema/package.json
  packages/schema/src/schema/geojsonsource.json
Labels: maintenance

#239 Fix shippping of geojson schema
  .gitignore
  packages/base/package.json
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  packages/schema/cacheGeoJSONSchema.js
  packages/schema/src/schema/geojsonsource.json
Labels: bug

#234 Annotations
  examples/buildings.jGIS
  examples/earthquakes.jGIS
  examples/france_hiking.jGIS
  examples/geotiff.jGIS
  examples/hillshade.jGIS
  examples/image.jGIS
  examples/pmtiles-raster.jGIS
  examples/pmtiles-vector.jGIS
  examples/shapefile.jGIS
  packages/base/package.json
  packages/base/src/annotations/components/Annotation.tsx
  packages/base/src/annotations/components/AnnotationFloater.tsx
  packages/base/src/annotations/components/Message.tsx
  packages/base/src/annotations/index.ts
  packages/base/src/annotations/model.ts
  packages/base/src/constants.ts
  packages/base/src/icons.ts
  packages/base/src/index.ts
  packages/base/src/mainview/mainView.tsx
  packages/base/src/mainview/mainviewmodel.ts
  packages/base/src/panelview/annotationPanel.tsx
  packages/base/src/panelview/components/filter-panel/Filter.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/jgis.json
  packages/schema/src/token.ts
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  python/jupytergis_core/src/index.ts
  python/jupytergis_core/src/jgisplugin/modelfactory.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_core/src/plugin.ts
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/src/index.ts
  python/jupytergis_lab/style/base.css
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  python/jupytergis_qgis/jupytergis_qgis/qgis_ydoc.py
  python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py
  ui-tests/playwright.config.js
  ui-tests/tests/annotations.spec.ts
  ui-tests/tests/gis-files/annotation-test.jGIS
  ui-tests/tests/gis-files/context-test.jGIS
  ui-tests/tests/gis-files/empty-france.jGIS
  ui-tests/tests/gis-files/filter-test.jGIS
  ui-tests/tests/gis-files/france-hiking.jGIS
  ui-tests/tests/gis-files/panel-test.jGIS
  ui-tests/tests/gis-files/shapefile-test.jGIS
  ui-tests/tests/gis-files/test.jGIS
  yarn.lock
Labels: enhancement

#241 Do not rely on collaborative drive for external file reading
  examples/france_regions.json
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  packages/schema/package.json
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_core/src/factory.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_qgis/src/plugins.ts
  yarn.lock
Labels: bug

#249 Apply pre-commit autofixes
  docs/collab.rst
  packages/base/rasterlayer_gallery/raster_layer_gallery.json
  python/jupytergis_lab/jupytergis_lab/__init__.py
  python/jupytergis_qgis/jupytergis_qgis/handlers.py
Labels: maintenance

#252 Replace @jupyterlab/rjsf with FormComponent from @jupyterlab/ui-components
  packages/base/package.json
  packages/base/src/commands.ts
  packages/base/src/formbuilder/formselectors.ts
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/geotiffsource.ts
  packages/base/src/panelview/components/filter-panel/Filter.tsx
  packages/base/src/panelview/components/filter-panel/FilterRow.tsx
  packages/base/style/base.css
  packages/base/style/dialog.css
  python/jupytergis_lab/style/base.css
  ui-tests/tests/contextmenu.spec.ts
  ui-tests/tests/geojson-layers.spec.ts
  yarn.lock
Labels: maintenance

#243 Emphasize the hidden layer icon
  packages/base/src/panelview/components/layers.tsx
  packages/base/style/icons/nonvisibility.svg
  packages/base/style/icons/visibility.svg
  packages/base/style/leftPanel.css
Labels: enhancement

#255 Grey out symbology entry for unsupported layers
  packages/base/src/commands.ts
Labels: maintenance

#260 Set expectation that RTC doesn't work yet in JupyterLite deployment
  README.md
Labels: documentation

#262 Speed-up GeoTIFF file handling
  packages/base/src/dialogs/symbology/tiff_layer/types/SingleBandPseudoColor.tsx
  packages/base/src/mainview/mainView.tsx
  packages/base/src/tools.ts
Labels: enhancement

#257 Follow a collaborator's viewport
  packages/base/src/mainview/FollowIndicator.tsx
  packages/base/src/mainview/mainView.tsx
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  ui-tests/tests/filters.spec.ts-snapshots/no-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/one-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/two-filter-linux.png
  ui-tests/tests/geojson-layers.spec.ts-snapshots/geoJSON-layer-linux.png
  ui-tests/tests/gis-files/annotation-test.jGIS
  ui-tests/tests/gis-files/context-test.jGIS
  ui-tests/tests/gis-files/empty-france.jGIS
  ui-tests/tests/gis-files/filter-test.jGIS
  ui-tests/tests/gis-files/france-hiking.jGIS
  ui-tests/tests/gis-files/panel-test.jGIS
  ui-tests/tests/gis-files/shapefile-test.jGIS
  ui-tests/tests/gis-files/test.jGIS
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
Labels: enhancement

#264 Show collaborators' cursors on map
  packages/base/src/annotations/components/AnnotationFloater.tsx
  packages/base/src/mainview/CollaboratorPointers.tsx
  packages/base/src/mainview/mainView.tsx
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_lab/style/base.css
Labels: enhancement

#278 Bump actions/upload-artifact to v4
  .github/workflows/build.yml
Labels: maintenance
