Repository geojupyter/jupytergis, pull requests merged in 2024-08, with the labels that each got.

#88 Fix the layer order by making a copy of the array before reversing it
  packages/base/src/panelview/components/layers.tsx
Labels: bug

#86 Commands refactor
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/formbuilder/creationform.tsx
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  packages/base/src/toolbar/widget.tsx
  packages/base/style/icons/geojson.svg
  packages/base/style/icons/raster.svg
  packages/schema/src/schema/rasterDemSource.json
  packages/schema/src/schema/rastersource.json
  packages/schema/src/schema/vectortilesource.json
  packages/schema/src/schema/videoSource.json
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/src/index.ts
  ui-tests/tests/contextmenu.spec.ts
  ui-tests/tests/geojson-layers.spec.ts
  ui-tests/tests/new-file.spec.ts
Labels: maintenance

#90 Drag and drop layers
  packages/base/src/commands.ts
  packages/base/src/panelview/components/layers.tsx
  packages/base/style/leftPanel.css
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  ui-tests/tests/left-panel.spec.ts
Labels: enhancement

#97 Attempt to fix the bot behavior
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#96 Add Scale to the basemap
  packages/base/src/mainview/mainview.tsx
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jGIS-linux.png
Labels: enhancement

#91 Add URL/tiles distinction and PM Tiles support
  examples/pmtiles-rasterDem.jGIS
  examples/pmtiles-vector.jGIS
  package.json
  packages/base/src/mainview/mainview.tsx
  packages/schema/src/schema/rasterDemSource.json
  ui-tests/tests/contextmenu.spec.ts
  ui-tests/tests/gis-files/context-test.jGIS
  ui-tests/tests/gis-files/panel-test.jGIS
  ui-tests/tests/left-panel.spec.ts
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebooks/Notebook.ipynb
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jGIS-linux.png
  yarn.lock
Labels: enhancement

#92 Add filtering in layers
  examples/earthquakes.jGIS
  examples/eq.json
  examples/test.jGIS
  packages/base/package.json
  packages/base/src/mainview/mainview.tsx
  packages/base/src/panelview/components/filter-panel/Filter.tsx
  packages/base/src/panelview/components/filter-panel/FilterRow.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/base/src/tools.ts
  packages/base/style/base.css
  packages/base/style/filterPanel.css
  packages/schema/src/doc.ts
  packages/schema/src/schema/jgis.json
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  ui-tests/tests/filters.spec.ts
  ui-tests/tests/filters.spec.ts-snapshots/no-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/one-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/two-filter-linux.png
  ui-tests/tests/gis-files/eq.json
  ui-tests/tests/gis-files/filter-test.jGIS
  yarn.lock
Labels: enhancement

#101 Fix layer removal bug
  packages/base/src/commands.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
Labels: bug

#103 Add StateDB to save UI state
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/leftpanel.tsx
  python/jupytergis_lab/src/index.ts
Labels: enhancement

#105 Terrain: allow to really exaggerate by removing the maximum
  packages/base/src/dialogs/terrainDialog.tsx
Labels: enhancement

#106 Update JupyterLite examples
  .github/workflows/build.yml
Labels: documentation

#107 Fix examples + fix filters schema + proper file validation error message
  examples/3d_terrain.jGIS
  packages/schema/src/model.ts
  packages/schema/src/schema/jgis.json
Labels: documentation

#108 Fix select bug when creatng mutltiple new layers
  packages/base/src/panelview/components/layers.tsx
Labels: bug

#89 Automatically infer source layer from Vector tile
  .github/workflows/build.yml
  .github/workflows/test.yml
  environment-dev.yml
  packages/base/src/dialogs/formdialog.tsx
  packages/base/src/formbuilder/creationform.tsx
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  packages/base/src/formbuilder/objectform/layerform.ts
  packages/base/src/formbuilder/objectform/vectorlayerform.ts
  packages/base/src/mainview/mainview.tsx
  packages/base/src/tools.ts
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/tests/__init__.py
  python/jupytergis_lab/jupytergis_lab/notebook/tests/test_api.py
  python/jupytergis_lab/jupytergis_lab/notebook/utils.py
  python/jupytergis_lab/pyproject.toml
Labels: enhancement

#111 Update repo links
  CONTRIBUTING.md
  docs/source/conf.py
  package.json
  packages/base/package.json
  packages/schema/package.json
  python/jupytergis_core/package.json
  python/jupytergis_lab/package.json
Labels: maintenance

#113 Add try/except case in the gallery building
  packages/base/rasterlayer_gallery_generator.py
Labels: bug

#78 Allow opening basic QGIS files
  .github/workflows/build.yml
  .github/workflows/update_galata_references.yaml
  .gitignore
  examples/buildings.qgz
  lerna.json
  package.json
  pyproject.toml
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  python/jupytergis_core/tests/utils.py
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_qgis/.gitignore
  python/jupytergis_qgis/.prettierignore
  python/jupytergis_qgis/LICENSE
  python/jupytergis_qgis/README.md
  python/jupytergis_qgis/install.json
  python/jupytergis_qgis/jupyter-config/server-config/jupytergis_qgis.json
  python/jupytergis_qgis/jupytergis_qgis/__init__.py
  python/jupytergis_qgis/jupytergis_qgis/handlers.py
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  python/jupytergis_qgis/jupytergis_qgis/qgis_ydoc.py
  python/jupytergis_qgis/jupytergis_qgis/tests/__init__.py
  python/jupytergis_qgis/jupytergis_qgis/tests/files/project0.qgs
  python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py
  python/jupytergis_qgis/package.json
  python/jupytergis_qgis/pyproject.toml
  python/jupytergis_qgis/scripts/bump-version.py
  python/jupytergis_qgis/setup.py
  python/jupytergis_qgis/src/index.ts
  python/jupytergis_qgis/src/modelfactory.ts
  python/jupytergis_qgis/src/plugins.ts
  python/jupytergis_qgis/style/base.css
  python/jupytergis_qgis/style/index.css
  python/jupytergis_qgis/style/index.js
  python/jupytergis_qgis/tsconfig.json
  scripts/build_packages.py
  scripts/dev-install.py
  ui-tests/tests/gis-files/buildings.qgs
  ui-tests/tests/gis-files/buildings.qgz
  ui-tests/tests/ui.spec.ts
  yarn.lock
Labels: enhancement

#104 #35 Add shapefile support
  packages/base/package.json
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/mainview/mainview.tsx
  packages/base/src/toolbar/widget.tsx
  packages/schema/src/schema/jgis.json
  packages/schema/src/schema/shapefileSource.json
  packages/schema/src/types.ts
  python/jupytergis_core/jupyter-config/server-config/jupytergis_core.json
  python/jupytergis_core/jupytergis_core/__init__.py
  python/jupytergis_core/jupytergis_core/handler.py
  python/jupytergis_core/pyproject.toml
  yarn.lock
Labels: enhancement

#116 Fix UI tests
  .github/workflows/build.yml
  ui-tests/tests/left-panel.spec.ts
  ui-tests/tests/ui.spec.ts
Labels: maintenance
