Repository geojupyter/jupytergis, pull requests merged in 2024-10, with the labels that each got.

#164 Add test for ShapeFiles
  examples/shapefile.jGIS
  ui-tests/tests/gis-files/shapefile-test.jGIS
  ui-tests/tests/ui.spec.ts
Labels: maintenance

#168 Fix the export path
  python/jupytergis_qgis/jupytergis_qgis/handlers.py
Labels: bug

#167 Animate spinner when fetching band information
  packages/base/src/dialogs/components/symbology/SingleBandPseudoColor.tsx
  packages/base/style/symbologyDialog.css
Labels: enhancement

#169 Use file from test directory only in UI tests
  ui-tests/tests/layer-browser.spec.ts
Labels: maintenance

#170 Remove terrain logic
  examples/buildings.jGIS
  examples/earthquakes.jGIS
  examples/france_hiking.jGIS
  examples/geotiff.jGIS
  examples/geotiff.qgz
  examples/hillshade.jGIS
  examples/image.jGIS
  examples/pmtiles-raster.jGIS
  examples/pmtiles-vector.jGIS
  examples/shapefile.jGIS
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/dialogs/terrainDialog.tsx
  packages/base/style/base.css
  packages/base/style/terrainDialog.css
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/jgis.json
  python/jupytergis_core/jupytergis_core/jgis_ydoc.py
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_qgis/jupytergis_qgis/qgis_ydoc.py
  ui-tests/tests/gis-files/context-test.jGIS
  ui-tests/tests/gis-files/empty-france.jGIS
  ui-tests/tests/gis-files/filter-test.jGIS
  ui-tests/tests/gis-files/france-hiking.jGIS
  ui-tests/tests/gis-files/panel-test.jGIS
  ui-tests/tests/gis-files/shapefile-test.jGIS
  ui-tests/tests/gis-files/test.jGIS
Labels: maintenance

#171 Add jupytergis_qgis to metapackage
  python/jupytergis/pyproject.toml
Labels: enhancement

#172 Exclude notebooks and qgz files from the lite deployment
  .github/workflows/build.yml
Labels: maintenance

#175 Export tif
  packages/base/src/dialogs/components/symbology/SingleBandPseudoColor.tsx
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
Labels: enhancement

#179 Add JupyterGIS icons in the filebrowser
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_qgis/src/plugins.ts
Labels: enhancement

#180 Rename launcher item
  python/jupytergis_core/src/jgisplugin/plugins.ts
  ui-tests/tests/new-file.spec.ts
Labels: enhancement

#183 Add `logoicon` as tab icon
  python/jupytergis_core/src/jgisplugin/plugins.ts
Labels: enhancement

#184 Remove extra comma from JSON repr
  python/jupytergis_core/src/jgisplugin/plugins.ts
Labels: bug

#188 Use appsharing for testing jupyterlite from PRs and galata reports
  .github/workflows/build.yml
  .github/workflows/comment-on-pr.yml
Labels: maintenance

#192 Set collaborative attribute to False in Jupyterlite
  packages/schema/src/model.ts
  python/jupytergis_core/src/jgisplugin/modelfactory.ts
  python/jupytergis_qgis/src/modelfactory.ts
Labels: bug

#193 Symbology refactor
  examples/earthquakes.jGIS
  examples/geotiff.jGIS
  packages/base/src/commands.ts
  packages/base/src/dialogs/components/symbology/BandRendering.tsx
  packages/base/src/dialogs/symbology/classificationModes.ts
  packages/base/src/dialogs/symbology/components/color_ramp/CanvasSelectComponent.tsx
  packages/base/src/dialogs/symbology/components/color_ramp/ColorRamp.tsx
  packages/base/src/dialogs/symbology/components/color_ramp/ColorRampEntry.tsx
  packages/base/src/dialogs/symbology/components/color_ramp/ModeSelectRow.tsx
  packages/base/src/dialogs/symbology/components/color_stops/StopContainer.tsx
  packages/base/src/dialogs/symbology/components/color_stops/StopRow.tsx
  packages/base/src/dialogs/symbology/hooks/useGetProperties.ts
  packages/base/src/dialogs/symbology/symbologyDialog.tsx
  packages/base/src/dialogs/symbology/symbologyUtils.ts
  packages/base/src/dialogs/symbology/tiff_layer/TiffRendering.tsx
  packages/base/src/dialogs/symbology/tiff_layer/components/BandRow.tsx
  packages/base/src/dialogs/symbology/tiff_layer/types/SingleBandPseudoColor.tsx
  packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx
  packages/base/src/dialogs/symbology/vector_layer/components/ValueSelect.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Categorized.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/SimpleSymbol.tsx
Labels: enhancement
