Repository geojupyter/jupytergis, pull requests merged in 2025-08, with the labels that each got.

#844 Support Graduated, Categorised & Canonical Symbology on VectorTiles
  packages/base/src/dialogs/symbology/hooks/useGetProperties.ts
  packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/mainview/mainView.tsx
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
Labels: enhancement

#850 Improve releasing docs
  docs/contributor_guide/how-tos/release.md
Labels: documentation

#855 Add a flag to hide STAC browser
  packages/base/src/panelview/leftpanel.tsx
Labels: enhancement

#883 Add user story issue template
  .github/ISSUE_TEMPLATE/0-user-story.yml
Labels: maintenance

#895 Rename "Identify Features" panel tab -> "Identified Features" (#893)
  packages/base/src/panelview/rightpanel.tsx
  ui-tests/tests/geojson-layers.spec.ts-snapshots/geoJSON-layer-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-chromium-linux.png
Labels: enhancement

#901 Lazy load gdal
  packages/base/src/gdal.ts
Labels: enhancement

#880 Legends for Vector Layers
  packages/base/src/dialogs/symbology/hooks/useGetSymbology.ts
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/components/legendItem.tsx
  packages/base/style/leftPanel.css
Labels: enhancement

#904 Adding Checkbox for reverse Color Ramp
  packages/base/src/dialogs/symbology/symbologyUtils.ts
  packages/base/src/dialogs/symbology/vector_layer/types/Categorized.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Heatmap.tsx
Labels: enhancement

#909 Add some information to the user on how to use the identify tool
  packages/base/src/panelview/components/identify-panel/IdentifyPanel.tsx
Labels: enhancement

#886 Add cmocean colormaps, fix bug when switching render type
  .eslintrc.js
  packages/base/src/dialogs/symbology/colorRampUtils.ts
  packages/base/src/dialogs/symbology/components/color_ramp/CanvasSelectComponent.tsx
  packages/base/src/dialogs/symbology/components/color_ramp/ColorRamp.tsx
  packages/base/src/dialogs/symbology/components/color_ramp/cmocean.json
  packages/base/src/dialogs/symbology/components/color_stops/StopContainer.tsx
  packages/base/src/dialogs/symbology/components/color_stops/StopRow.tsx
  packages/base/src/dialogs/symbology/symbologyDialog.tsx
  packages/base/src/dialogs/symbology/symbologyUtils.ts
  packages/base/src/dialogs/symbology/tiff_layer/types/SingleBandPseudoColor.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/types.ts
  packages/base/src/types/colormap.d.ts
  packages/base/tsconfig.json
Labels: enhancement
