Repository geojupyter/jupytergis, pull requests merged in 2025-06, with the labels that each got.

#728 Support importing from path alias `@`
  packages/base/package.json
  packages/base/src/annotations/components/Annotation.tsx
  packages/base/src/console/consoleview.ts
  packages/base/src/dialogs/ProcessingFormDialog.tsx
  packages/base/src/dialogs/layerCreationFormDialog.tsx
  packages/base/src/dialogs/symbology/components/color_stops/StopContainer.tsx
  packages/base/src/dialogs/symbology/components/color_stops/StopRow.tsx
  packages/base/src/dialogs/symbology/hooks/useGetBandInfo.ts
  packages/base/src/dialogs/symbology/hooks/useGetProperties.ts
  packages/base/src/dialogs/symbology/tiff_layer/TiffRendering.tsx
  packages/base/src/dialogs/symbology/tiff_layer/components/BandRow.tsx
  packages/base/src/dialogs/symbology/tiff_layer/types/MultibandColor.tsx
  packages/base/src/dialogs/symbology/tiff_layer/types/SingleBandPseudoColor.tsx
  packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Canonical.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Categorized.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Heatmap.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/SimpleSymbol.tsx
  packages/base/src/formbuilder/creationform.tsx
  packages/base/src/formbuilder/editform.tsx
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/fileselectorwidget.tsx
  packages/base/src/formbuilder/objectform/layer/heatmapLayerForm.ts
  packages/base/src/formbuilder/objectform/layer/layerform.ts
  packages/base/src/formbuilder/objectform/process/dissolveProcessForm.tsx
  packages/base/src/formbuilder/objectform/source/geojsonsource.ts
  packages/base/src/formbuilder/objectform/source/geotiffsource.ts
  packages/base/src/formbuilder/objectform/source/pathbasedsource.ts
  packages/base/src/formbuilder/objectform/source/sourceform.ts
  packages/base/src/mainview/TemporalSlider.tsx
  packages/base/src/mainview/mainView.tsx
  packages/base/src/panelview/annotationPanel.tsx
  packages/base/src/panelview/components/filter-panel/Filter.tsx
  packages/base/src/panelview/components/identify-panel/IdentifyPanel.tsx
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/model.ts
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/base/src/statusbar/StatusBar.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/src/tools.ts
  packages/base/tsconfig.json
  yarn.lock
Labels: maintenance

#736 Fix file rename in side panels
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_core/src/factory.ts
Labels: bug

#740 Processing : Centroids of a vector layer
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/dialogs/ProcessingFormDialog.tsx
  packages/base/src/processing.ts
  packages/schema/src/schema/processing/centroids.json
  packages/schema/src/types.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/src/index.ts
Labels: enhancement

#743 Fix LayoutRestorer entries
  python/jupytergis_lab/src/index.ts
Labels: bug, Needs Port To JupyterCAD

#746 new feature request template
  .github/ISSUE_TEMPLATE/4-feature-request.yml
Labels: maintenance

#714 Refactor vector symbology: Configure radius and color separately
  packages/base/src/dialogs/symbology/components/color_ramp/ColorRamp.tsx
  packages/base/src/dialogs/symbology/symbologyDialog.tsx
  packages/base/src/dialogs/symbology/tiff_layer/types/SingleBandPseudoColor.tsx
  packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Categorized.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/SimpleSymbol.tsx
  packages/base/src/types.ts
  python/jupytergis_lab/style/base.css
Labels: enhancement

#771 Change the version of xeus (#759)
  docs/environment-docs.yml
Labels: maintenance

#576 Add architecture docs
  docs/contributor_guide/architecture.md
  docs/contributor_guide/index.md
Labels: documentation, help wanted

#787 Increased the width of main-panel in notebook viewer
  packages/base/src/mainview/mainView.tsx
Labels: enhancement
