Repository geojupyter/jupytergis, pull requests merged in 2025-05, with the labels that each got.

#676 Make the console toolbar button a toggle button
  packages/base/src/commands.ts
  packages/base/src/widget.ts
Labels: enhancement

#671 Remove SourcePanel
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/panelview/components/sources.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/style/leftPanel.css
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/src/index.ts
  ui-tests/tests/left-panel.spec.ts
  ui-tests/tests/new-file.spec.ts
Labels: enhancement

#680 Fix mistakes in explorer basemap names
  python/jupytergis_lab/jupytergis_lab/notebook/explore.py
Labels: bug

#679 Add issue templates: experience report, bug, docs, blank issue
  .github/ISSUE_TEMPLATE/1-experience-report.yml
  .github/ISSUE_TEMPLATE/2-bug.yml
  .github/ISSUE_TEMPLATE/3-docs.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: maintenance

#683 Reset UI-tests snapshots
  .github/workflows/build.yml
  examples/jgis.ipynb
  ui-tests/package.json
  ui-tests/tests/filters.spec.ts-snapshots/no-filter-chromium-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/no-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/one-filter-chromium-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/one-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/two-filter-chromium-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/two-filter-linux.png
  ui-tests/tests/geojson-layers.spec.ts-snapshots/geoJSON-layer-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-notebook-chromium-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-notebook-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-shapefile-jGIS-chromium-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-shapefile-jGIS-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-test-jGIS-chromium-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-test-jGIS-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/ui.spec.ts-snapshots/Render-test-jGIS-linux.png
Labels: bug

#684 Update releasing docs
  RELEASE.md
  docs/contributor_guide/releasing.md
Labels: documentation

#672 Simplify Symbology of Vectors
  packages/base/src/dialogs/symbology/symbologyUtils.ts
  packages/base/src/dialogs/symbology/vector_layer/types/Categorized.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/SimpleSymbol.tsx
  packages/base/src/tools.ts
  packages/schema/src/schema/project/layers/vectorTileLayer.json
  packages/schema/src/schema/project/layers/vectorlayer.json
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  ui-tests/tests/geojson-layers.spec.ts
Labels: enhancement

#637 Don't Save annotation as stringified json
  packages/base/src/annotations/model.ts
  packages/base/src/mainview/mainView.tsx
  packages/schema/src/interfaces.ts
Labels: bug

#697 Prevent duplication of color steps when reopening the symbology panel
  packages/base/src/dialogs/symbology/symbologyUtils.ts
Labels: bug

#700 SymbologyPanel: Update Stop Rows based on Methods instead of just setting them
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
Labels: bug

#703 Support Symbology on VectorTileLayers
  packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/SimpleSymbol.tsx
  packages/base/src/mainview/mainView.tsx
Labels: bug

#707 Fix blank menu after selecting heatmap
  packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Categorized.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/SimpleSymbol.tsx
Labels: bug

#713 Implement new "Canonical" render type for vector layers
  packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Canonical.tsx
  packages/base/src/tools.ts
Labels: enhancement

#708 Auto-save project when updating any property
  packages/base/src/formbuilder/editform.tsx
  packages/base/src/formbuilder/objectform/baseform.tsx
Labels: enhancement

#723 Remove UsersItem component and use the one from `@jupyter/collaboration`
  .github/workflows/build.yml
  packages/base/package.json
  packages/base/src/toolbar/index.ts
  packages/base/src/toolbar/usertoolbaritem.tsx
  packages/base/src/toolbar/widget.tsx
  yarn.lock
Labels: maintenance
