Repository geojupyter/jupytergis, pull requests merged in 2025-03, with the labels that each got.

#524 Fix releaser for publishing jupytergis-lite
  pyproject.toml
Labels: bug

#510 Processing PoC - Buffer
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/formbuilder/formbuilder.tsx
  packages/base/src/formbuilder/processingformdialog.tsx
  packages/base/src/formbuilder/utils.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/schema/buffer.json
  packages/schema/src/types.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_lab/src/index.ts
Labels: enhancement, hackathon

#522 Add new user-facing interpolate source property
  packages/base/src/mainview/mainView.tsx
  packages/schema/src/schema/geoTiffSource.json
  packages/schema/src/schema/imageSource.json
  packages/schema/src/schema/rasterDemSource.json
  packages/schema/src/schema/rastersource.json
Labels: enhancement

#529 Explicit buffer processing distance unit
  packages/schema/src/schema/buffer.json
Labels: enhancement

#543 Docs: upgrading micromamba
  .readthedocs.yaml
Labels: documentation

#528 Enable downloading a vectorlayer
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/formbuilder/formdialog.tsx
  packages/base/src/tools.ts
  packages/schema/src/schema/exportGeojson.json
  packages/schema/src/schema/exportGeotiff.json
  packages/schema/src/types.ts
  python/jupytergis_lab/src/index.ts
Labels: enhancement

#542 organise `schema/`
  packages/schema/schema.js
  packages/schema/src/doc.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/export/exportGeojson.json
  packages/schema/src/schema/export/exportGeotiff.json
  packages/schema/src/schema/processing/buffer.json
  packages/schema/src/schema/project/jgis.json
  packages/schema/src/schema/project/layers/heatmapLayer.json
  packages/schema/src/schema/project/layers/hillshadeLayer.json
  packages/schema/src/schema/project/layers/imageLayer.json
  packages/schema/src/schema/project/layers/rasterlayer.json
  packages/schema/src/schema/project/layers/vectorTileLayer.json
  packages/schema/src/schema/project/layers/vectorlayer.json
  packages/schema/src/schema/project/layers/webGlLayer.json
  packages/schema/src/schema/project/sources/geoTiffSource.json
  packages/schema/src/schema/project/sources/imageSource.json
  packages/schema/src/schema/project/sources/rasterDemSource.json
  packages/schema/src/schema/project/sources/rastersource.json
  packages/schema/src/schema/project/sources/shapefileSource.json
  packages/schema/src/schema/project/sources/vectortilesource.json
  packages/schema/src/schema/project/sources/videoSource.json
  packages/schema/src/types.ts
  packages/schema/tsconfig.json
  python/jupytergis_lab/jupytergis_lab/notebook/objects/__init__.py
  python/jupytergis_lab/pyproject.toml
Labels: maintenance

#555 Add quickstart to installation doc
  docs/user_guide/install.md
  docs/user_guide/install.rst
Labels: documentation

#553 Disable identify tool when we can't identify
  packages/base/src/commands.ts
  packages/base/src/panelview/leftpanel.tsx
Labels: enhancement

#550 Processing: Add `Dissolve` Command & A better Form structure for Processing Commands
  examples/world.jGIS
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/dialogs/ProcessingFormDialog.tsx
  packages/base/src/dialogs/layerBrowserDialog.tsx
  packages/base/src/dialogs/layerCreationFormDialog.tsx
  packages/base/src/formbuilder/editform.tsx
  packages/base/src/formbuilder/formbuilder.tsx
  packages/base/src/formbuilder/formdialog.tsx
  packages/base/src/formbuilder/formselectors.ts
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/dissolveProcessForm.tsx
  packages/base/src/formbuilder/objectform/fileselectorwidget.tsx
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  packages/base/src/formbuilder/objectform/geotiffsource.ts
  packages/base/src/formbuilder/objectform/layerform.ts
  packages/base/src/formbuilder/objectform/pathbasedsource.ts
  packages/base/src/formbuilder/objectform/sourceform.ts
  packages/base/src/formbuilder/objectform/tilesourceform.ts
  packages/base/src/formbuilder/utils.ts
  packages/base/src/index.ts
  packages/schema/src/schema/dissolve.json
  python/jupytergis_lab/src/index.ts
Labels: enhancement

#556 Fix API doc build
  .readthedocs.yaml
  docs/user_guide/features/index.md
  pyproject.toml
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  scripts/build_packages.py
Labels: documentation

#563 Remove reprojection from buffer operation
  packages/base/src/commands.ts
  packages/schema/src/schema/processing/buffer.json
Labels: enhancement

#562 Enable ruff's bugbear "B" ruleset
  pyproject.toml
  python/jupytergis_core/jupytergis_core/__init__.py
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/y_connector.py
  python/jupytergis_qgis/jupytergis_qgis/__init__.py
Labels: maintenance

#557 Create requirements-docs.md for building local docs workflow
  docs/contributor_guide/docs.md
  docs/contributor_guide/index.md
Labels: documentation

#566 Fix docs build warning: Adjust documentation headings to start at H1
  docs/contributor_guide/docs.md
Labels: documentation

#568 Update lockfile
  yarn.lock
Labels: maintenance

#572 Organise forms
  .eslintrc.js
  packages/base/src/dialogs/ProcessingFormDialog.tsx
  packages/base/src/formbuilder/editform.tsx
  packages/base/src/formbuilder/formselectors.ts
  packages/base/src/formbuilder/index.ts
  packages/base/src/formbuilder/objectform/layer/heatmapLayerForm.ts
  packages/base/src/formbuilder/objectform/layer/hillshadeLayerForm.ts
  packages/base/src/formbuilder/objectform/layer/index.ts
  packages/base/src/formbuilder/objectform/layer/layerform.ts
  packages/base/src/formbuilder/objectform/layer/vectorlayerform.ts
  packages/base/src/formbuilder/objectform/layer/webGlLayerForm.tsx
  packages/base/src/formbuilder/objectform/process/dissolveProcessForm.tsx
  packages/base/src/formbuilder/objectform/process/index.ts
  packages/base/src/formbuilder/objectform/source/geojsonsource.ts
  packages/base/src/formbuilder/objectform/source/geotiffsource.ts
  packages/base/src/formbuilder/objectform/source/index.ts
  packages/base/src/formbuilder/objectform/source/pathbasedsource.ts
  packages/base/src/formbuilder/objectform/source/sourceform.ts
  packages/base/src/formbuilder/objectform/source/tilesourceform.ts
Labels: maintenance

#571 Restore local geotiff file support
  packages/base/src/dialogs/symbology/hooks/useGetBandInfo.ts
  packages/base/src/formbuilder/objectform/source/geotiffsource.ts
  packages/base/src/mainview/mainView.tsx
  packages/base/src/tools.ts
Labels: enhancement

#573 Make Output Layer name configurable for processing
  packages/base/src/commands.ts
  packages/base/src/dialogs/ProcessingFormDialog.tsx
  packages/schema/src/schema/processing/dissolve.json
  packages/schema/src/types.ts
  python/jupytergis_qgis/src/plugins.ts
Labels: enhancement

#578 Refactor Processing Logic to make it modular
  packages/base/src/commands.ts
  packages/base/src/dialogs/ProcessingFormDialog.tsx
  packages/base/src/processing.ts
Labels: enhancement, maintenance

#581 Feat:- Adding key shortcut i to identity
  packages/base/src/keybindings.json
Labels: enhancement
