Repository geojupyter/jupytergis, pull requests merged in 2025-04, with the labels that each got.

#584 Add documentation build script, fix build warning, and update docs on building docs
  .readthedocs.yaml
  docs/build.sh
  docs/contributor_guide/docs.md
  docs/environment-docs.yml
Labels: documentation, maintenance

#570 Convert docs rst to myst
  docs/changelog.md
  docs/changelog.rst
  docs/conf.py
  docs/contributor_guide/development_setup.md
  docs/contributor_guide/development_setup.rst
  docs/contributor_guide/docs.md
  docs/index.md
  docs/user_guide/features/collab.md
  docs/user_guide/features/extension.md
  docs/user_guide/features/extension.rst
  docs/user_guide/python_api.md
Labels: documentation

#600 Temporarily change identify keybinding to "Accel+I" to work around bug #592
  packages/base/src/keybindings.json
Labels: bug

#589 Processing: Option to save output layer by the side
  packages/base/src/commands.ts
  packages/base/src/dialogs/ProcessingFormDialog.tsx
  packages/base/src/processing.ts
  packages/schema/src/schema/processing/buffer.json
  packages/schema/src/schema/processing/dissolve.json
Labels: enhancement

#606 Fix pointer to show correct updated location
  packages/base/src/mainview/mainView.tsx
Labels: bug

#603 Use only relevant selectors for keybindings to prevent conflicts
  packages/base/src/keybindings.json
  packages/base/src/mainview/mainView.tsx
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/rightpanel.tsx
  python/jupytergis_lab/src/index.ts
Labels: bug

#607 Enable adding annotations on QGZ files
  python/jupytergis_qgis/src/modelfactory.ts
  python/jupytergis_qgis/src/plugins.ts
Labels: bug

#611 Use Accel I temporarily
  packages/base/src/keybindings.json
Labels: bug

#615 Pin docprovider
  python/jupytergis/pyproject.toml
  requirements-build.txt
Labels: bug

#617 Fix tabs rendering in Contributor Guide
  docs/contributor_guide/development_setup.md
Labels: documentation

#586 Add contributor how-to: Editing keybindings
  docs/contributor_guide/how-tos/index.md
  docs/contributor_guide/how-tos/keybindings/index.md
  docs/contributor_guide/index.md
Labels: documentation

#621 Add contributor how-to: Editing commands
  docs/contributor_guide/how-tos/commands/index.md
Labels: documentation

#608 Add collaborative session creation guide
  docs/user_guide/features/collab.md
  docs/user_guide/tutorials/02-collaboration/index.md
Labels: documentation

#627 Use svg icons for the main view toolbar
  packages/base/src/constants.ts
  packages/base/src/icons.ts
  packages/base/src/toolbar/widget.tsx
  packages/base/style/icons/book_open.svg
  packages/base/style/icons/clock-solid.svg
  packages/base/style/icons/info-solid.svg
  packages/base/style/icons/raster.svg
  packages/base/style/icons/terminal_toolbar.svg
  packages/base/style/icons/vector_square.svg
  ui-tests/tests/filters.spec.ts-snapshots/no-filter-chromium-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/one-filter-chromium-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/two-filter-chromium-linux.png
  ui-tests/tests/geojson-layers.spec.ts-snapshots/geoJSON-layer-chromium-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-notebook-chromium-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-shapefile-jGIS-chromium-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-test-jGIS-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-chromium-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-chromium-linux.png
Labels: enhancement

#633 Remove work-in-progress warning from README
  python/jupytergis/README.md
Labels: documentation

#635 Try fixing notebook on lite by pinning `my-jupyter-shared-drive<0.2.0`
  docs/environment.yml
  lite/environment.yml
  packages/base/style/icons/info-solid.svg
  python/jupytergis_lite/pyproject.toml
Labels: bug, maintenance

#636 Try fixing layer browser ui-tests
  ui-tests/tests/layer-browser.spec.ts
Labels: bug, maintenance

#626 New toolbar button: Center on user's geolocation
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/icons.ts
  packages/base/src/mainview/mainView.tsx
  packages/base/src/mainview/mainviewmodel.ts
  packages/base/src/toolbar/widget.tsx
  packages/base/style/icons/geolocation.svg
  packages/base/style/icons/target_with_center.svg
  packages/base/style/icons/target_without_center.svg
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  ui-tests/tests/geojson-layers.spec.ts
Labels: enhancement

#640 Improved Annotation UX
  packages/base/src/annotations/components/AnnotationFloater.tsx
  packages/base/src/annotations/model.ts
  packages/base/src/mainview/mainView.tsx
  packages/schema/src/interfaces.ts
  ui-tests/tests/annotations.spec.ts
Labels: enhancement

#632 Document how to run tests locally (and when you shouldn't)
  docs/contributor_guide/index.md
  docs/contributor_guide/testing.md
Labels: documentation

#643 Fill vertical space in linked output & sidecar views
  python/jupytergis_lab/style/base.css
Labels: enhancement

#658 Alphabetically sort feature properties in IdentifyPanel
  packages/base/src/panelview/components/identify-panel/IdentifyPanel.tsx
Labels: bug

#649 Interactive Identify Panel
  packages/base/src/mainview/mainView.tsx
  packages/base/src/panelview/components/identify-panel/IdentifyPanel.tsx
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_lab/style/base.css
Labels: enhancement

#650 Some fixes in Annotation UX
  packages/base/src/mainview/mainView.tsx
  packages/base/src/panelview/annotationPanel.tsx
  python/jupytergis_lab/style/base.css
Labels: bug, enhancement

#660 Allow passing source ID
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
Labels: enhancement

#659 Indicate the point being identified on GeoTiFF
  packages/base/src/mainview/mainView.tsx
  packages/base/src/panelview/components/identify-panel/IdentifyPanel.tsx
  python/jupytergis_lab/style/base.css
Labels: enhancement

#665 Initialize map view from model's lat/lon/zoom
  packages/base/src/mainview/mainView.tsx
Labels: bug

#666 Allow initializing a `GISDocument` that has a path
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
Labels: enhancement

#670 Remove source while removing layer
  packages/schema/src/model.ts
Labels: enhancement
