Repository geojupyter/jupytergis, pull requests merged in 2025-01, with the labels that each got.

#274 Automatically upgrade GitHub Action dependencies with Dependabot
  .github/dependabot.yml
Labels: maintenance

#279 Configure lerna to use `jlpm` as npm client
  docs/contributing.rst
  lerna.json
Labels: documentation

#275 Build docs and Lite deployment in ReadTheDocs
  .github/workflows/build.yml
  .github/workflows/comment-on-pr.yml
  .github/workflows/pr-rtd-link.yml
  .readthedocs.yaml
  docs/environment-docs.yml
  docs/index.rst
Labels: help wanted, maintenance

#273 Add checks for reST content
  .pre-commit-config.yaml
  docs/contributing.rst
Labels: documentation, maintenance

#285 Fix typo in ReadTheDocs PR link automation
  .github/workflows/pr-rtd-link.yml
Labels: maintenance

#282 Make prettier output more human readable, improve documentation of linting
  .github/pull_request_template.md
  docs/contributing.rst
  package.json
Labels: maintenance

#290 Temporary PR comment for lite preview
  .github/workflows/pr-rtd-link.yml
Labels: maintenance

#292 Shrink logo and add lite badge to readme
  README.md
Labels: documentation

#284 Refactor layer tree updates
  packages/base/src/panelview/components/layers.tsx
  packages/schema/src/model.ts
Labels: bug

#269 Improve layer update logic
  packages/base/src/mainview/mainView.tsx
Labels: maintenance

#301 Remove unnecessary jupyterlab install
  docs/contributing.rst
Labels: documentation

#297 Use image layer in python API
  examples/Notebook.ipynb
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
Labels: bug

#305 Fix bug when loading geojson layers in notebook and update notebook test
  packages/base/src/mainview/mainView.tsx
  ui-tests/tests/notebook.spec.ts
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebooks/Notebook.ipynb
Labels: bug

#304 Add Hillshade layer to notebook api
  packages/schema/src/schema/rasterDemSource.json
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/objects/__init__.py
Labels: enhancement

#298 Add issue linkage to PR checklist
  .github/pull_request_template.md
Labels: maintenance

#256 Local and external file loading support for geojson, image and shapefile sources
  examples/local.jGIS
  examples/nyc.zip
  examples/radar.gif
  packages/base/src/dialogs/symbology/hooks/useGetProperties.ts
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  packages/base/src/mainview/mainView.tsx
  packages/base/src/panelview/components/filter-panel/Filter.tsx
  packages/base/src/tools.ts
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_core/src/factory.ts
Labels: enhancement

#294 Add zoom to layer to layer context menu
  packages/base/src/annotations/components/Annotation.tsx
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/mainview/mainView.tsx
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  python/jupytergis_lab/src/index.ts
  ui-tests/tests/contextmenu.spec.ts
Labels: enhancement

#325 Use slider to set opacity in layer form
  package.json
  packages/base/src/formbuilder/objectform/baseform.tsx
  yarn.lock
Labels: enhancement

#320 Add keyboard shortcuts for undo and redo
  packages/base/src/commands.ts
  packages/base/src/keybindings.json
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/tsconfig.json
  python/jupytergis_lab/src/index.ts
Labels: bug

#332 Try fixing jupyterlite deployment
  python/jupytergis_lab/package.json
Labels: bug

#333 Move dependencies from root to dependent package + Update JupyterLite in lite build
  .github/workflows/build.yml
  docs/environment-docs.yml
  package.json
  packages/base/package.json
  python/jupytergis_lab/package.json
  yarn.lock
Labels: bug

#337 QGIS logo added.
  packages/base/src/icons.ts
  packages/base/style/icons/logo_mini_qgz.svg
  python/jupytergis_qgis/src/plugins.ts
Labels: enhancement

#303 Support Python 3.12 & Drop support for 3.8 and 3.9
  .github/workflows/build.yml
  .readthedocs.yaml
  binder/environment.yml
  docs/environment-docs.yml
  python/jupytergis/pyproject.toml
  python/jupytergis_core/pyproject.toml
  python/jupytergis_lab/pyproject.toml
  python/jupytergis_qgis/pyproject.toml
Labels: enhancement, maintenance

#343 Register new projections if needed when adding layers
  packages/base/src/mainview/mainView.tsx
Labels: bug

#346 Fix JupyterGISDoc.setSource
  packages/schema/src/doc.ts
Labels: bug

#345 Include files in lite deployment for `local.jGIS`
  docs/conf.py
Labels: bug

#335 Multiple ways to create layers
  packages/base/src/commands.ts
  packages/base/src/dialogs/formdialog.tsx
  packages/base/src/formbuilder/creationform.tsx
  packages/base/src/formbuilder/editform.tsx
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/fileselectorwidget.tsx
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  packages/base/src/formbuilder/objectform/layerform.ts
  packages/base/src/mainview/mainView.tsx
  packages/schema/src/interfaces.ts
  packages/schema/src/schema/imageSource.json
  python/jupytergis_core/src/plugin.ts
  python/jupytergis_core/src/schemaregistry.ts
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
Labels: enhancement

#354 Add Proper Styling to Symbology panel's "mode"
  packages/base/src/dialogs/symbology/components/color_ramp/ModeSelectRow.tsx
Labels: enhancement

#356 Fix Lite Deployment Badge via RTD on PR using Custom Action
  .github/workflows/pr-rtd-link.yml
Labels: documentation

#361 Add a pretty JupyterLite button to docs
  .pre-commit-config.yaml
  docs/assets/css/custom.css
  docs/conf.py
  docs/index.rst
Labels: documentation

#364 Disable Image Smoothing for `ImageSource`
  packages/base/src/mainview/mainView.tsx
Labels: bug

#362 Add Path Validation for `ShapefileSource` and `ImageSource`.
  packages/base/src/formbuilder/creationform.tsx
  packages/base/src/formbuilder/editform.tsx
  packages/base/src/formbuilder/formselectors.ts
  packages/base/src/formbuilder/objectform/baseform.tsx
  packages/base/src/formbuilder/objectform/fileselectorwidget.tsx
  packages/base/src/formbuilder/objectform/geojsonsource.ts
  packages/base/src/formbuilder/objectform/pathbasedsource.ts
  packages/base/src/tools.ts
Labels: enhancement

#366 Keep extension package name extension-artifacts for 3.12 to fix bot
  .github/workflows/build.yml
Labels: maintenance

#368 Bot: missing collaboration package
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#348 Add status bar to map
  packages/base/src/mainview/mainView.tsx
  packages/base/src/statusbar/StatusBar.tsx
  packages/base/style/base.css
  packages/base/style/statusBar.css
  python/jupytergis_lab/style/base.css
  ui-tests/tests/filters.spec.ts-snapshots/no-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/one-filter-linux.png
  ui-tests/tests/filters.spec.ts-snapshots/two-filter-linux.png
  ui-tests/tests/geojson-layers.spec.ts-snapshots/geoJSON-layer-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
Labels: enhancement

#373 Use `interpolate` property to Disable Image Smoothing for `ImageLayers`
  packages/base/src/mainview/mainView.tsx
Labels: enhancement

#365 Add numerical input next to the slider and handle value 1-10
  packages/base/src/formbuilder/objectform/baseform.tsx
Labels: bug, enhancement

#360 Multi band symbology
  packages/base/src/dialogs/symbology/hooks/useGetBandInfo.ts
  packages/base/src/dialogs/symbology/tiff_layer/TiffRendering.tsx
  packages/base/src/dialogs/symbology/tiff_layer/components/BandRow.tsx
  packages/base/src/dialogs/symbology/tiff_layer/types/MultibandColor.tsx
  packages/base/src/dialogs/symbology/tiff_layer/types/SingleBandPseudoColor.tsx
  packages/schema/src/schema/webGlLayer.json
Labels: enhancement

#379 Proper Styling Added for OK Button
  packages/base/style/base.css
Labels: bug

#378 Support path lib objects
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/y_connector.py
Labels: bug, enhancement

#382 Move jupyterlab dependency from jupytergis_lab to jupytergis
  .github/workflows/build.yml
  python/jupytergis/pyproject.toml
  python/jupytergis_lab/pyproject.toml
  requirements-build.txt
Labels: maintenance

#339 Extend caching for image, geoJSON & shapeFiles
  packages/base/src/tools.ts
Labels: enhancement

#392 Restore rich Sphinx contributing doc, link from GitHub-Markdown doc
  CONTRIBUTING.md
  docs/contributing.rst
Labels: documentation

#400 Fix name typo `notebookRenderePlugin` -> `notebookRendererPlugin`
  python/jupytergis_lab/src/index.ts
  python/jupytergis_lab/src/notebookrenderer.ts
Labels: maintenance

#402 Create a new file from the Python API
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/tests/test_api.py
Labels: bug, Needs Port To JupyterCAD

#406 Fix shared document interface
  packages/schema/src/interfaces.ts
Labels: maintenance, Needs Port To JupyterCAD

#409 Upgrade jupyter-ydoc python to match the npm version
  python/jupytergis_core/pyproject.toml
  python/jupytergis_lab/pyproject.toml
  python/jupytergis_qgis/pyproject.toml
Labels: maintenance

#408 Fix scale indicator in notebooks and symbology overflow
  packages/base/src/dialogs/symbology/vector_layer/types/Heatmap.tsx
  packages/base/src/formbuilder/objectform/vectorlayerform.ts
  packages/base/src/mainview/mainView.tsx
  packages/base/style/symbologyDialog.css
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-linux.png
Labels: bug

#413 Remove source layer stuff
  examples/buildings.jGIS
  packages/base/src/formbuilder/objectform/vectorlayerform.ts
  packages/base/src/panelview/components/filter-panel/Filter.tsx
  packages/base/src/tools.ts
  packages/schema/src/schema/vectorTileLayer.json
  packages/schema/src/schema/vectorlayer.json
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/tests/test_api.py
  python/jupytergis_lab/jupytergis_lab/notebook/utils.py
  python/jupytergis_lab/pyproject.toml
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py
Labels: maintenance

#390 Support exporting vectorLayer to qgis
  examples/roads.jGIS
  examples/world.jGIS
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py
Labels: enhancement

#410 Rework add layer toolbar menu
  packages/base/src/toolbar/widget.tsx
  ui-tests/tests/geojson-layers.spec.ts
Labels: enhancement

#391 Add error handling
  packages/base/src/commands.ts
  packages/base/src/mainview/mainView.tsx
Labels: enhancement

#417 Replace input field for selected file path with text
  packages/base/src/formbuilder/objectform/fileselectorwidget.tsx
  python/jupytergis_lab/style/base.css
Labels: bug

#393 added simple tutorial to introduce the jupyterGIS GUI.
  .github/workflows/build.yml
  docs/assets/images/CreateShapefileLayer.png
  docs/assets/images/JGIS_editor.png
  docs/assets/images/OpenLayerBrowser.png
  docs/assets/images/addVectorLayer.png
  docs/assets/images/adjustSymbology.png
  docs/assets/images/editSymbology.png
  docs/assets/images/finalIntroMap.png
  docs/assets/images/hideLayer.png
  docs/assets/images/jupyterGIS_interface.png
  docs/assets/images/renameLayer.png
  docs/assets/images/renameSource.png
  docs/assets/images/renamejGIS.png
  docs/assets/images/severalShapefileLayers.png
  docs/assets/images/viewShapefileLayer.png
  docs/assets/images/wrongLayerOrder.png
  docs/conf.py
  docs/environment-docs.yml
  docs/index.rst
  docs/tutorials/intro.md
Labels: documentation
