Repository geojupyter/jupytergis, pull requests merged in 2025-02, with the labels that each got.

#423 Remove test to expect warning on vectorLayer export
  ui-tests/tests/export.spec.ts
Labels: maintenance

#430 Fix categorized symbology
  examples/roads.jGIS
  examples/world.jGIS
  packages/base/src/dialogs/symbology/vector_layer/types/Categorized.tsx
Labels: bug

#428 Re-organize docs navigation and add releasing guide
  CHANGELOG.md
  docs/contributor_guide/code_quality.rst
  docs/contributor_guide/development_setup.rst
  docs/contributor_guide/index.md
  docs/contributor_guide/releasing.md
  docs/contributor_guide/troubleshooting.rst
  docs/index.rst
  docs/user_guide/features/collab.rst
  docs/user_guide/features/extension.rst
  docs/user_guide/features/index.md
  docs/user_guide/index.md
  docs/user_guide/install.rst
  docs/user_guide/python_api.rst
  docs/user_guide/tutorials/index.md
  docs/user_guide/tutorials/intro.md
Labels: documentation

#440 Fix link to contribution docs
  CONTRIBUTING.md
  docs/user_guide/install.rst
  docs/user_guide/tutorials/intro.md
Labels: documentation, maintenance

#442 Replace broken shapefile from ui tests
  docs/user_guide/tutorials/intro.md
  examples/shapefile.jGIS
  ui-tests/tests/gis-files/shapefile-test.jGIS
Labels: maintenance

#443 Fix slider sync issue
  packages/base/src/formbuilder/objectform/baseform.tsx
Labels: bug

#446 Add Docker install instructions
  README.md
  docs/user_guide/install.rst
Labels: documentation

#419 Widget with toolbar and sidepanel in cell output
  packages/base/src/annotations/components/Annotation.tsx
  packages/base/src/annotations/model.ts
  packages/base/src/commands.ts
  packages/base/src/dialogs/formdialog.tsx
  packages/base/src/dialogs/layerBrowserDialog.tsx
  packages/base/src/dialogs/symbology/hooks/useGetBandInfo.ts
  packages/base/src/dialogs/symbology/symbologyDialog.tsx
  packages/base/src/dialogs/symbology/tiff_layer/TiffRendering.tsx
  packages/base/src/dialogs/symbology/tiff_layer/types/MultibandColor.tsx
  packages/base/src/dialogs/symbology/tiff_layer/types/SingleBandPseudoColor.tsx
  packages/base/src/dialogs/symbology/vector_layer/VectorRendering.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Categorized.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Heatmap.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/SimpleSymbol.tsx
  packages/base/src/formbuilder/creationform.tsx
  packages/base/src/formbuilder/editform.tsx
  packages/base/src/formbuilder/objectform/fileselectorwidget.tsx
  packages/base/src/mainview/mainviewwidget.tsx
  packages/base/src/panelview/annotationPanel.tsx
  packages/base/src/panelview/components/filter-panel/Filter.tsx
  packages/base/src/panelview/components/identify-panel/IdentifyPanel.tsx
  packages/base/src/panelview/components/layers.tsx
  packages/base/src/panelview/components/sources.tsx
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/panelview/model.ts
  packages/base/src/panelview/objectproperties.tsx
  packages/base/src/panelview/rightpanel.tsx
  packages/base/src/types.ts
  packages/base/src/widget.ts
  packages/schema/src/interfaces.ts
  python/jupytergis_core/src/factory.ts
  python/jupytergis_core/src/jgisplugin/plugins.ts
  python/jupytergis_core/src/plugin.ts
  python/jupytergis_lab/package.json
  python/jupytergis_lab/src/index.ts
  python/jupytergis_lab/src/notebookrenderer.ts
  python/jupytergis_qgis/src/plugins.ts
  ui-tests/tests/notebook.spec.ts
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/dark-Notebook-ipynb-cell-3-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-0-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-1-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
  ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-3-linux.png
  yarn.lock
Labels: enhancement, Needs Port To JupyterCAD

#448 Fix a typo in gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
Labels: bug

#449 Bump yjs-widgets to >=0.3.9
  python/jupytergis_lab/package.json
  python/jupytergis_lab/pyproject.toml
  yarn.lock
Labels: maintenance

#450 Fix collab view bug
  packages/base/src/mainview/mainView.tsx
Labels: bug

#412 Enable Python API in the JupyterLite deployment
  .github/workflows/build.yml
  .readthedocs.yaml
  README.md
  docs/conf.py
  docs/environment-docs.yml
  docs/environment.yml
  docs/jupyter-lite.json
  packages/base/src/widget.ts
  python/jupytergis_core/src/jgisplugin/modelfactory.ts
  python/jupytergis_lab/jupytergis_lab/__init__.py
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/tests/test_api.py
  python/jupytergis_lab/jupytergis_lab/notebook/utils.py
  python/jupytergis_lab/package.json
  python/jupytergis_lab/pyproject.toml
  python/jupytergis_lab/src/notebookrenderer.ts
  yarn.lock
Labels: enhancement, Needs Port To JupyterCAD

#451 Add jupytergis-lite metapackage
  .github/workflows/build.yml
  README.md
  docs/environment.yml
  docs/user_guide/tutorials/intro.md
  examples/Notebook.ipynb
  examples/vector_colors.ipynb
  packages/base/src/widget.ts
  pyproject.toml
  python/jupytergis_lab/src/notebookrenderer.ts
  python/jupytergis_lite/LICENSE
  python/jupytergis_lite/README.md
  python/jupytergis_lite/jupytergis/__init__.py
  python/jupytergis_lite/pyproject.toml
  python/jupytergis_lite/scripts/bump-version.py
  python/jupytergis_lite/setup.py
  scripts/build_packages.py
  scripts/dev-install.py
  ui-tests/tests/notebooks/Notebook.ipynb
Labels: enhancement, Needs Port To JupyterCAD

#459 Updating version of proj4-list
  packages/base/package.json
  packages/base/src/mainview/mainView.tsx
Labels: maintenance

#460 Pin meta-package dependencies
  python/jupytergis/pyproject.toml
  python/jupytergis/scripts/bump-version.py
  python/jupytergis_lite/pyproject.toml
  python/jupytergis_lite/scripts/bump-version.py
Labels: bug

#463 Continue installing the labextension in the dev install script
  scripts/dev-install.py
  yarn.lock
Labels: maintenance

#421 Time slider
  examples/earthquakes.jGIS
  packages/base/package.json
  packages/base/src/commands.ts
  packages/base/src/constants.ts
  packages/base/src/dialogs/symbology/hooks/useGetProperties.ts
  packages/base/src/dialogs/symbology/vector_layer/types/Categorized.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Graduated.tsx
  packages/base/src/formbuilder/objectform/heatmapLayerForm.ts
  packages/base/src/mainview/TemporalSlider.tsx
  packages/base/src/mainview/mainView.tsx
  packages/base/src/mainview/mainviewmodel.ts
  packages/base/src/panelview/leftpanel.tsx
  packages/base/src/toolbar/widget.tsx
  packages/base/src/tools.ts
  packages/base/src/widget.ts
  packages/base/style/base.css
  packages/base/style/temporalSlider.css
  packages/schema/src/interfaces.ts
  packages/schema/src/model.ts
  packages/schema/src/schema/heatmapLayer.json
  packages/schema/src/schema/jgis.json
  python/jupytergis_lab/src/index.ts
  python/jupytergis_lab/src/notebookrenderer.ts
  python/jupytergis_lab/style/base.css
  yarn.lock
Labels: enhancement

#464 Fix bump script for jupytergis-lite
  python/jupytergis_lite/scripts/bump-version.py
Labels: bug, Needs Port To JupyterCAD

#470 Fix "Try it with JupyterLite" button in user guide
  .pre-commit-config.yaml
  docs/assets/css/custom.css
  docs/index.rst
  docs/user_guide/index.md
Labels: bug

#475 Update user guide tutorial
  docs/assets/images/CreateShapefileLayer.png
  docs/assets/images/addVectorLayer.png
  docs/user_guide/tutorials/intro.md
Labels: documentation

#477 Install JupyterGIS metapackage in Update snapshots workflow
  .github/workflows/update_galata_references.yaml
Labels: maintenance

#479 Convert the Troubleshooting document to MyST
  docs/contributor_guide/troubleshooting.md
  docs/contributor_guide/troubleshooting.rst
Labels: documentation

#478 Add `remove_layer` method to Python `GISDocument` API
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/tests/test_api.py
Labels: enhancement

#485 Disable smoothing on all raster sources
  packages/base/src/mainview/mainView.tsx
Labels: enhancement

#490 Separate bot for lite snapshots update
  .github/workflows/update_lite_galata_references.yaml
Labels: maintenance

#491 Use `dist/` while using lite-artifacts
  .github/workflows/update_lite_galata_references.yaml
Labels: maintenance

#489 Configure ui-tests for lite deployment
  .github/workflows/build.yml
  examples/jgis.ipynb
  examples/shapefile.jGIS
  examples/test.jGIS
  lite/environment.yml
  lite/jupyter-lite.json
  lite/jupyter_lite_config.json
  scripts/build_packages.py
  ui-tests/package.json
  ui-tests/playwright-lite.config.js
  ui-tests/playwright.config.js
  ui-tests/tests/lite.spec.ts
  ui-tests/tests/lite.spec.ts-snapshots/Render-notebook-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-shapefile-jGIS-linux.png
  ui-tests/tests/lite.spec.ts-snapshots/Render-test-jGIS-linux.png
  ui-tests/yarn.lock
Labels: maintenance

#499 Put commandRegistry back in consoleOptions
  packages/base/src/widget.ts
Labels: bug

#503 Fix COG performances
  examples/europe_geotiff.jGIS
  packages/base/src/dialogs/symbology/hooks/useGetBandInfo.ts
  packages/base/src/dialogs/symbology/tiff_layer/components/BandRow.tsx
  packages/base/src/formbuilder/objectform/geotiffsource.ts
  packages/base/src/mainview/mainView.tsx
  packages/base/src/tools.ts
Labels: bug

#506 Fix examples in JupyterLite
  examples/earthquakes.jGIS
  examples/europe_geotiff.jGIS
  examples/vector_colors.ipynb
Labels: bug

#507 Fix to vector colors notebook
  examples/vector_colors.ipynb
Labels: bug

#508 Gallery: Add ESRI maps
  packages/base/rasterlayer_gallery/Esri-NatGeoWorldMap.png
  packages/base/rasterlayer_gallery/Esri-OceanBasemap.png
  packages/base/rasterlayer_gallery/Esri-WorldGrayCanvas.png
  packages/base/rasterlayer_gallery/Esri-WorldImagery.png
  packages/base/rasterlayer_gallery/Esri-WorldPhysical.png
  packages/base/rasterlayer_gallery/Esri-WorldShadedRelief.png
  packages/base/rasterlayer_gallery/Esri-WorldStreetMap.png
  packages/base/rasterlayer_gallery/Esri-WorldTerrain.png
  packages/base/rasterlayer_gallery/Esri-WorldTopoMap.png
  packages/base/rasterlayer_gallery/OpenStreetMap-CAT.png
  packages/base/rasterlayer_gallery/raster_layer_gallery.json
  packages/base/rasterlayer_gallery_generator.py
Labels: enhancement

#511 Removing misleading comment
  docs/user_guide/tutorials/intro.md
Labels: documentation
