Repository geojupyter/jupytergis, pull requests merged in 2025-07, with the labels that each got.

#796 Fix lint errors :bell:
  docs/contributor_guide/code_quality.md
  docs/contributor_guide/troubleshooting.md
  docs/user_guide/features/collab.md
  docs/user_guide/tutorials/02-collaboration/index.md
Labels: documentation, maintenance

#798 Indicate to user when running the JS and Python type generation steps
  packages/schema/package.json
Labels: maintenance

#799 Add JSON validity pre-commit check
  .pre-commit-config.yaml
Labels: maintenance

#800 Add 'New JupyterGIS file' option to context menu
  python/jupytergis_core/src/jgisplugin/plugins.ts
  ui-tests/tests/new-file.spec.ts
Labels: enhancement

#805 Remove platform/product selections when no longer relevant
  packages/base/src/stacBrowser/components/StacFilterSection.tsx
  packages/base/src/stacBrowser/components/StacPanelFilters.tsx
  packages/base/style/stacBrowser.css
Labels: bug

#812 Restore follow mode
  packages/base/src/toolbar/widget.tsx
  python/jupytergis_lab/style/base.css
Labels: bug

#816 Update update_galata_references.yml github action file
  .github/workflows/update_galata_references.yaml
  .github/workflows/update_lite_galata_references.yaml
Labels: bug

#727 Add GeoParquet support
  examples/geoparquet.jgis
  packages/base/package.json
  packages/base/src/commands/BaseCommandIDs.ts
  packages/base/src/commands/index.ts
  packages/base/src/constants.ts
  packages/base/src/formbuilder/formselectors.ts
  packages/base/src/mainview/mainView.tsx
  packages/base/src/menus.ts
  packages/base/src/tools.ts
  packages/base/src/types/geoparquet.d.ts
  packages/base/tsconfig.json
  packages/schema/src/schema/project/jgis.json
  packages/schema/src/schema/project/sources/geoParquetSource.json
  packages/schema/src/types.ts
  python/jupytergis_core/jupytergis_core/schema/__init__.py
  python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py
  python/jupytergis_lab/jupytergis_lab/notebook/tests/test_api.py
  yarn.lock
Labels: enhancement

#828 Change default colormap from 'cool' to 'viridis'
  packages/base/src/dialogs/symbology/components/color_ramp/ColorRamp.tsx
  packages/base/src/dialogs/symbology/vector_layer/types/Heatmap.tsx
  packages/schema/src/schema/project/layers/heatmapLayer.json
  packages/schema/src/schema/project/layers/vectorLayer.json
  packages/schema/src/schema/project/layers/webGlLayer.json
  python/jupytergis_qgis/jupytergis_qgis/qgis_loader.py
  python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py
Labels: enhancement
